services:
  - type: web
    name: mrdevil-oauth
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FB_APP_ID
        sync: false
      - key: FB_APP_SECRET
        sync: false
      - key: REDIRECT_URI
        value: https://mrdevil-oauth.onrender.com/callback
